create: add-guard
tutiyaren/php-practice pull request #8
Opened 2024-03-09 04:47 UTC by tutiyaren

2024-03-10 22:26 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2024-03-10 22:26 UTC, KatsuyaTanaka95 commented on src/public/guard.php
> +    }
ガード節で解くようにしましょう！

自力で解決できていて素晴らしいです！！
この研修では、普段からガード節で書くようにお願いしたいです！
理由としては、、良い現場ではガード節で書くことになるからです！！
（ガード節で書けないと、、レベルの高いエンジニアからこの人とは働きたくないと思われてしまいます！！😭😱）

2024-03-11 11:42 UTC, tutiyaren commented
ガード節を使用したコードに修正しました！ご確認お願いします。

2024-03-11 23:57 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2024-03-11 23:57 UTC, KatsuyaTanaka95 commented on src/public/guard.php
> +    }
if文の中にif文が入らないように書いてみましょう！！

2024-03-12 11:41 UTC, tutiyaren commented
ガード節を使用したコードに修正しました！ご確認お願いします。

ガード節は今まで扱ったことないのでいまいち考えつきづらいです、、笑
elseは使用しないのが普通になってくるという認識でよろしかったでしょうか？

2024-03-12 14:20 UTC, KatsuyaTanaka95 approved these changes
ご修正ありがとうございます！
LGTMです！！！
mergeしちゃいましょ〜🙆🙋😊🌟💫

ガード節は慣れていないと考えづらいですよね！！
elseは使用しないのが普通になってくるという認識であってます！！

2024-03-13 12:34 UTC, merged