create: foreach-if_1
tutiyaren/php-practice pull request #9
Opened 2024-03-09 05:14 UTC by tutiyaren

2024-03-10 22:30 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2024-03-10 22:30 UTC, KatsuyaTanaka95 commented on src/public/foreach-if_1.php
> +}
こちらもガード節で書いてみましょう！！！

2024-03-11 11:30 UTC, tutiyaren commented
if ($score < 30) {
        $resultList[] = $subject . 'は不合格';
        continue;
}
$resultList[] = $subject . 'は合格';

上記のように修正しました！ご確認お願いします。

2024-03-11 23:58 UTC, KatsuyaTanaka95 approved these changes
ご修正ありがとうございます！
LGTMです！！！
mergeしちゃいましょ〜🙆🙋😊🌟💫

2024-03-12 03:03 UTC, merged